# Site Settings
baseurl: ""
url : "https://muddassirahmedkhan.github.io/"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Muddassir Ahmed Khan
    description : A dynamic and focused Software Developer and Tech Lead with a proven track record in the software industry. Has 5 years of experience in the domain of AI-powered iOS and Android applications. Is currently a member of the Innovation Team at Callsign which innovates in the domains of Passive Authentication, Fraud Prevention, and Intelligence-based Identification.
    experience :
      - start : April 2021
        end : Preset
        organization: Callsign
        role: iOS/Android Developer
        logoImage: assets/callsign_logo.svg
    skills : 
      - skill : Android & iOS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  muddassir.ahmed235@gmail.com
    linkedin:  # Full URL 
    github: muddassir235
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
